<script>
	/*
	@TODO: Make into an "endless" clicker game -- the "workers" will be algorithmically randomly generated such that:
			* Their prod (normalized in res/s) always increases by a defined (or geometrically/exponentially increasing) interval
			* Their interval between prod output continually goes up by a set interval (or increasing, as above)
			* Their names are randomly generated from some data source (dictionary)
			* Maybe implement some random image generation thing for them?
			* Thresholds are determined algorithmically by some equation, not hard coded in as below, so they continue infinitely
			* Costs increase by some set interval or increasing interval
			* Introduce some random fluctuations into how productivity can be upgraded, intervals shortened, and prod/interval for new workers
					* (but make sure normalized res/s always increasing)
		@TODO: Introduce way to save progress (just need to save res, num workers, upgrades, basically just save state)
		@TODO: Introduce incremental DOM beautification with increasing clicker upgrades, also algorithmically generated
			* Some way to visualize increases in the "population" of your workers and increase in resources
		@TODO: Add other resources which can be autogenerated, eventually make new resources themselves algorithmically generated (again, so game goes forever)
	*/
	const PTHRESH = [0, 10, 200, 4000, 80000, 1600000, 32000000];
	
	let paradigm = 0;
	let res = 0;
	
	let gen1 = 0;
	let gen1Cost = 10;
	let gen1Prod = 0.5; //each worker producer 0.5 res /s
	
	let totalProd = 0; //total res automatically produced /s
	
	function clicked() {
		res += 1;
	}
	function reset() {
		res = 0;
		paradigm = 0;
		workers = 0;
	}
	function addGen1() {
		res -= gen1Cost;
		gen1 += 1;
		gen1Cost = gen1Cost * 1.5;
		updateTotalProd("gen1")
	}
	
	function updateTotalProd(worker) {
		switch(worker) {
			case "gen1":
				totalProd += gen1Prod;
				break;
		}
	}
	
	function autoprodRes() {
		res += totalProd
	}
	setInterval(autoprodRes, 1000)
	
	
	/* Paradigms */
	$: if (res > PTHRESH[1] && res <= PTHRESH[2]) {
		paradigm = 1;
	} else if (res > PTHRESH[2] && res <= PTHRESH[3]) {
		paradigm = 2;
	} else if (res > PTHRESH[3] && res <= PTHRESH[4]) {
		paradigm = 3;
	} else if (res > PTHRESH[4] && res <= PTHRESH[5]) {
		paradigm = 4;
	} else if (res > PTHRESH[5] && res <= PTHRESH[6]) {
		paradigm = 5;
	}
</script>

<h1>Paradigm {paradigm}</h1>
<p><b>Resources: </b> {res}</p>
<p><b>Productivity: </b> {totalProd} res per second</p>
<p>
	<button on:click={clicked}>
	Increase res
</button>
</p>
<hr/>
<!-- GEN 1 ---------------------------------------- -->
<p>
	<button on:click={addGen1}>
	Add worker (cost: {gen1Cost}, #: {gen1}, prod: {gen1Prod})
</button> 
</p>
<p>
	<b>Gen 1 workers:</b> {gen1}   |   <b>Gen 1 productivity:</b> {gen1Prod}
</p>
<hr/>
<!-- SETTINGS ---------------------------------------- -->
<p>
<button on:click={reset}>
	Reset
</button>	
</p>

