<script>
	/*
	@TODO: Make into an "endless" clicker game -- the "workers" will be algorithmically randomly generated such that:
			* Their prod (normalized in res/s) always increases by a defined (or geometrically/exponentially increasing) interval
			* Their interval between prod output continually goes up by a set interval (or increasing, as above)
			* Their names are randomly generated from some data source (dictionary)
			* Maybe implement some random image generation thing for them?
			* Thresholds are determined algorithmically by some equation, not hard coded in as below, so they continue infinitely
			* Costs increase by some set interval or increasing interval
			* Introduce some random fluctuations into how productivity can be upgraded, intervals shortened, and prod/interval for new workers
					* (but make sure normalized res/s always increasing)
		@TODO: Introduce way to save progress (just need to save res, num workers, upgrades, basically just save state)
		@TODO: Introduce incremental DOM beautification with increasing clicker upgrades, also algorithmically generated
			* Some way to visualize increases in the "population" of your workers and increase in resources
		@TODO: Add other resources which can be autogenerated, eventually make new resources themselves algorithmically generated (again, so game goes forever)
	*/
	const PTHRESH = [0, 10, 200, 4000, 80000, 1600000, 32000000];
	
	let paradigm = 0;
	let res = 0;
    let upgradeExp = 1.15;
	
    //true productivity is prod/interval
    let clickProd = 1;
    let clickUpgradeProdExp = 1.1;
    let clickUpgradeCost = 100;
    let clickUpgradeCostExp = 1.15;
	let gen1 = 0;
	let gen1Cost = 10;
	let gen1Prod = 0.5; //each worker producer 0.5 res /s
    let gen1Interval = 1; //1s interval
    let gen2 = 0;
    let gen2Cost = 100;
    let gen2Prod = 25;
    let gen2Interval = 5;

	let totalProd = 0; //total res automatically produced /s
	
	function clicked() {
		res += clickProd;
	}
    function upgradeClick() {
        res -= clickUpgradeCost;
        clickProd = clickProd * clickUpgradeProdExp;
        clickUpgradeCost = clickUpgradeCost * clickUpgradeCostExp;
    }
	function reset() {
		res = 0;
		paradigm = 0;
        gen1 = 0;
        gen2 = 0;
        gen1Cost = 0;
        gen2Cost = 0;
	}
	function addGen1() {
		res -= gen1Cost;
		gen1 += 1;
		gen1Cost = gen1Cost * upgradeExp;
        updateTotalProd("gen1");
	}
    function addGen2() {
        res -= gen2Cost;
        gen2 += 1;
        gen2Cost = gen2Cost * upgradeExp;
        updateTotalProd("gen2");
    }
	
	function updateTotalProd(worker) {
		switch(worker) {
			case "gen1":
				totalProd += gen1Prod/gen1Interval;
				break;
            case "gen2":
                totalProd += gen2Prod/gen2Interval;
                break;
		}
	}
    	
	function gen1ResProd() {
		res += gen1Prod * gen1
	}
    setInterval(gen1ResProd, gen1Interval*1000);
	
    function gen2ResProd() {
        res += gen2Prod * gen2
    }
    setInterval(gen2ResProd, gen2Interval*1000);
	
	/* Paradigms */
    //@TODO: Make it so paradigms, once achieved, are permanent
    $: if (res > PTHRESH[paradigm+1]){
		paradigm++;
    }
</script>

<h1>Paradigm {paradigm}</h1>
<p><b>Resources: </b> {res}</p>
<p><b>Productivity: </b> {totalProd} res per second</p>
<p>
	<button on:click={clicked}>
        Increase res (produce {clickProd} res)
</button>
</p>
{#if paradigm > 2 && res > 0}
<p>
    <button on:click={upgradeClick}>
        Upgrade click prod to {clickProd*clickUpgradeProdExp}/click. Cost: {Math.floor(clickUpgradeCost)}
    </button>
</p>
{/if}
<hr/>
<!-- GEN 1 ---------------------------------------- -->
{#if paradigm > 0 && res > 0}
<p>
	<button on:click={addGen1}>
        Add Gen 1 (cost: {gen1Cost}, #: {gen1}, prod: {gen1Prod}/{gen1Interval}s)
</button> 
</p>
<p>
    <b>Gen 1 workers:</b> {gen1}&nbsp;|&nbsp;<b>Gen 1 productivity:</b> {gen1Prod}/{gen1Interval}s
</p>
<hr/>
{/if}
<!-- GEN 2 ---------------------------------------- -->
{#if paradigm > 1 && res > 0}
<p>
	<button on:click={addGen2}>
        Add Gen 2 (cost: {gen2Cost}, #: {gen2}, prod: {gen2Prod}/{gen2Interval}s)
</button> 
</p>
<p>
    <b>Gen 2 workers:</b> {gen2}&nbsp;|&nbsp;<b>Gen 2 productivity:</b> {gen1Prod}/{gen2Interval}s
</p>
<hr/>
{/if}
<!-- SETTINGS ---------------------------------------- -->
<p>
<button on:click={reset}>
	Reset
</button>	
</p>

